name: changes
on: 
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v1
            
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '2.7'
          
      - name: Run Script
        run: pylint


    
    
     
