name: changes
on:
  push:
  pull_request:
   types: [opened, edited]

jobs:
            
  Cppcheck:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Requirements
        run: |
         cat /etc/os-release
         sudo apt-get update -y
         sudo apt-get install -y cppcheck
      - name: Python Version 2
        run : cppcheck --version

  
  Python:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
         python-version: 3.7
    
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pylint --version
        
    - name: Python Version
      run : python --version
            pylint --version
      
  
  Shell:
    runs-on: ubuntu-latest
    steps: 
      
      - name: Install Requirements
        run: |
         sudo apt-get install shellcheck
    
      - name: Shellcheck Version
        run: shellcheck --version
