on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python --version
        sudo apt-get install pylint
        pylint test.py
        shellcheck --version
        cppcheck --version
        
