name: changes
on: 
  push:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs)"

      - name: echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}

    
    
     
