name: PyLint Runner

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
         python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        sudo apt-get install shellcheck
        pip install cppcheck
    - name: Run Pylint
      run: |
        cat .pylintrc
        pylint test.py
