on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        python --version
        python3 --version
        pylint --version
        shellcheck --version
        cppcheck --version
        
