name: changes
on:
  push:
  pull_request:
   types: [opened, edited]

jobs:
            
  Cppcheck:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Requirements
        run: |
         cat /etc/os-release
         sudo apt-get update -y
         sudo apt-get install -y cppcheck
      - name: Cppcheck Version
        run : cppcheck --version

  
  Python:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
         python-version: 3.7
    
    - name: Install Requirements
      run: |
        pip install pylint==2.4.4
        
    - name: Python & Pylint Version
      run : python --version
            pylint --version
      
  
  Shell:
    runs-on: ubuntu-latest
    steps: 
      
      - name: Install Requirements
        run: |
          sudo apt install xz-utils
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/v0.7.0/shellcheck-v0.7.0/linux.x86_64.tar.xz" | tar -xJv
          sudo cp "shellcheck-v0.7.0/shellcheck" /usr/bin/
          
      - name: Shellcheck Version
        run: shellcheck --version
