on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Clone Repository
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python --version
          sudo apt-get install pylint --fix missing
          pylint test.py
          sudo apt-get install shellcheck --fix missing
          shellcheck --version
          sudo apt-get install cppcheck --fix missing
          cppcheck --version
        
